In [12]:
    #Project – COSC 6334.001(2)
        
        
# To design and implement a system that finds the inverse of a matrix of size n x n with a running time complexity of O(n^3), 
# we can use the LU decomposition method with partial pivoting. The steps involved are as follows:
# 1. Input the matrix A from the user or generate it randomly with entries a(i,j) ∈ R, where n >= 20.
# 2. Check whether A is a square matrix, i.e., the number of rows and columns of A should be equal. If not, raise an error.
# 3. Check whether A is nonsingular, i.e., its determinant is nonzero. If the determinant is zero, then the matrix is singular,
# and the inverse cannot be computed. In this case, raise an error.
# 4. Perform LU decomposition of A with partial pivoting, which can be written as PA = LU, where P is a permutation matrix, 
# L is a lower triangular matrix with ones on the diagonal, and U is an upper triangular matrix. The LU decomposition can 
# be done using Gaussian elimination with partial pivoting, which has a time complexity of O(n^3).
# 5. Solve the equation LUX = B, where B is the identity matrix of size n x n. To do this, first solve the equation LY = B for 
# Y using forward substitution, and then solve UX = Y for X using back substitution. Forward and back substitution can be done
# in O(n^2) time.
# 6. The solution X obtained in step 5 is the inverse of A.

In [13]:
   #Import necessary libraries
import numpy as np

In [14]:

#Functions and Algorithms
def lu_decomposition(A):
    n = A.shape[0]
    P = np.identity(n)
    L = np.zeros((n, n))
    U = np.copy(A)

    for k in range(n-1):
        # partial pivoting
        pivot = np.argmax(np.abs(U[k:, k])) + k
        if pivot != k:
            U[[k, pivot], :] = U[[pivot, k], :]
            P[[k, pivot], :] = P[[pivot, k], :]

        # elimination
        L[k, k] = 1
        for i in range(k+1, n):
            factor = U[i, k] / U[k, k]
            L[i, k] = factor
            U[i, k:] -= factor * U[k, k:]

    L[-1, -1] = 1
    return P, L, U

def solve_linear_system(L, U, B):
    n = L.shape[0]
    Y = np.zeros((n, n))
    X = np.zeros((n, n))

    for j in range(n):
        # forward substitution
        Y[0, j] = B[0, j] / L[0, 0]
        for i in range(1, n):
            Y[i, j] = (B[i, j] - np.dot(L[i, :i], Y[:i, j])) / L[i, i]

        # back substitution
        X[-1, j] = Y[-1, j] / U[-1, -1]
        for i in range(n-2, -1, -1):
            X[i, j] = (Y[i, j] - np.dot(U[i, i+1:], X[i+1:, j])) / U[i, i]

    return X

# input matrix A from user or generate it randomly
n = int(input("Enter the dimension of the matrix: "))
A = np.random.rand(n, n)



Enter the dimension of the matrix: 20


In [8]:
# check whether A is square
if A.shape[0] != A.shape[1]:
    raise ValueError("Matrix A must be square")
    
# check whether A is nonsingular
if np.linalg.det(A) == 0:
    raise ValueError("Matrix A is singular and cannot be inverted")
    
# perform LU decomposition of A with partial pivoting
P, L, U = lu_decomposition(A)

# solve the equation LUX = B for X
B = np.identity(n)
X = solve_linear_system(L, U, B)

# print the inverse matrix
print("Inverse of A:\n", X)


Inverse of A:
 [[ 1.76298228e-01 -2.17109923e+00 -2.24748200e-01 -5.68000969e-01
  -1.53572569e+00  1.33330541e+00  1.57614314e+00 -1.72263915e+00
  -4.53978260e-01  1.26964265e+00  4.32670296e-01 -1.37483158e-01
   4.19987401e-01  9.24695083e-01 -8.41890930e-01  1.00487115e+00
  -5.97473374e-01  7.58005558e-01  4.42339733e-01  8.62554085e-01]
 [-6.86155767e-01  7.09339708e+00 -1.76729783e+00  2.60141986e+00
  -1.27134700e+00 -1.60745737e+00  5.62830541e-01  3.26405603e+00
  -9.60818786e-01 -3.00850014e+00 -3.19716219e-01 -4.27194652e-01
   3.49595605e-01 -7.89738055e-01  1.02046148e+00  5.91993237e-01
   1.96927069e-01  7.89799708e-01  2.66198841e-03 -2.08223662e+00]
 [-9.14831818e-01 -4.11921944e-01  9.54678593e-01 -9.92986150e-01
   1.70470021e+00  1.45774789e+00 -1.71585620e+00  1.81305373e+00
   4.11057812e-01  4.15560936e-01 -1.22756624e+00 -3.78190646e-01
   1.40714807e+00  1.21869612e+00 -3.20945629e-01  1.11629766e+00
  -5.38477149e-01 -4.22306455e-01 -4.97197527e-01 -1.403707

In [9]:
# To test the code with the provided data.csv file, 
# we can read in the data and use it as the input matrix A. 
# Here is the implementation.

# read in data from file
data = np.loadtxt("C:\\Users\\n\\Downloads\\DAA mvs project\\data (5).csv", delimiter=",")
n = data.shape[0]
print(data)

[[81. 28. 17. ... 91. 81. 90.]
 [90. 68. 79. ... 51. 19. 42.]
 [13. 65. 31. ... 97. 13. 36.]
 ...
 [64. 47. 13. ... 74. 56. 50.]
 [71.  2. 19. ... 52. 85. 43.]
 [75. 34. 24. ... 80. 56. 61.]]


In [10]:

# check whether A is square
if data.shape[0] != data.shape[1]:
    raise ValueError("Matrix A must be square")

# check whether A is nonsingular
if np.linalg.det(data) == 0:
    raise ValueError("Matrix A is singular and cannot be inverted")

# perform LU decomposition of A with partial pivoting
P, L, U = lu_decomposition(data)

In [11]:
# solve the equation LUX = B for X
B = np.identity(n)
X = solve_linear_system(L, U, B)

# print the inverse matrix
print("Inverse of A:\n", X)

Inverse of A:
 [[-1.53785731e-02  4.26434324e-03 -3.59838362e-02 ... -5.52408509e-04
  -2.86061396e-03  1.92814625e-04]
 [-2.90163291e-01  2.03972762e-01 -3.21389549e-01 ...  1.01809129e-02
  -1.78767619e-02  1.06339397e-02]
 [ 1.14652228e-01 -1.61386571e-01  1.92099230e-01 ...  4.07620174e-03
   2.70362129e-03 -2.21057902e-02]
 ...
 [ 1.06527042e-01 -4.18132188e-02  8.42500272e-02 ...  1.12524717e-02
  -3.01663175e-03 -6.35639828e-03]
 [ 1.73367354e-01 -2.01867680e-01  2.53564176e-01 ... -6.72698443e-03
   1.74355290e-02 -2.01926590e-02]
 [-2.01299036e-01  2.19020930e-01 -3.21609636e-01 ...  1.83917286e-03
  -4.80470024e-03  1.95482717e-02]]


In [ ]:
#THE END OF SYSTEM IMPLEMENTATION